name: Deploy Website

on:
  push:
    branches:
      - website-frontend-release

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: PROD
      url: https://denys.horman.tech
    defaults:
      run:
        working-directory: ./website/frontend
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - run: git lfs checkout
      - uses: actions/setup-node@v4
      - run: npm install
      - run: npm run compile-proto-files
      - run: npm run build
      - run: npm run minify-index
      - run: npm run single-bundle
      - env:
          FLEEK_API_KEY: ${{ secrets.FLEEK_API_KEY }}
        run: npm run deploy
